CREATE SEQUENCE "PUBLIC"."HIBERNATE_SEQUENCE" START WITH 1;

CREATE TABLE "PUBLIC"."LOCATION"(
    "ID" BIGINT NOT NULL,
    "ADDRESS" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."LOCATION" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_9" PRIMARY KEY("ID");

CREATE TABLE "PUBLIC"."PLACE"(
    "ID" BIGINT NOT NULL,
    "NAME" VARCHAR(255),
    "LOCATION_ID" BIGINT
);
ALTER TABLE "PUBLIC"."PLACE" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_4" PRIMARY KEY("ID");


CREATE TABLE "PUBLIC"."USER"(
    "ID" BIGINT NOT NULL,
    "EMAIL" VARCHAR(255),
    "FIRST_NAME" VARCHAR(255),
    "LAST_NAME" VARCHAR(255),
    "PASSWORD" VARCHAR(255),
    "PHONE" VARCHAR(255)
);
ALTER TABLE "PUBLIC"."USER" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");


CREATE TABLE "PUBLIC"."USER_ROLE"(
    "USER_ID" BIGINT NOT NULL,
    "ROLES" VARCHAR(255)
);

ALTER TABLE "PUBLIC"."PLACE" ADD CONSTRAINT "PUBLIC"."FKAXTBYDHVR0OEED7ORURUF0HN" FOREIGN KEY("LOCATION_ID") REFERENCES "PUBLIC"."LOCATION"("ID") NOCHECK;
ALTER TABLE "PUBLIC"."USER_ROLE" ADD CONSTRAINT "PUBLIC"."FK859N2JVI8IVHUI0RL0ESWS6O" FOREIGN KEY("USER_ID") REFERENCES "PUBLIC"."USER"("ID") NOCHECK;